### ISSUE TITLE
can not read pdf file

### ISSUE THREAD

**Issue by xinyi1989** [dbashford/textract#141]
when i read pdf file,the below error happend
extractor for type exists, but failed to initialize. Message: INFO: 'pdftotext' does not appear to be installed, so textract will be unable to extract PDFs.
    at extract (C:\personal\project\liguang\ricoh-service\node_modules\textract\lib\extract.js:147:15)
    at Timeout._onTimeout (C:\personal\project\liguang\ricoh-service\node_modules\textract\lib\extract.js:155:7)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) typeNotFound: true }
i have already intall pdftotext .

**Comment by dbashford** [comment]
From the same place you execute your code, can you run `pdftotext`?  This means it is somehow not available. Is it not on the PATH?

Going to close this, this is purely environmental and out of textract's control. Can keep the conversation going, though.
